import { Roboto_Mono as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { Theme } from "./theme/ThemeContext";
import { COOKIE } from "./cookies/cookies";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Next auth app',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = cookies().get(COOKIE.THEME);
  const defaultTheme = (themeCookie?.value as Theme) ?? 'dark';
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          `min-h-screen text-foreground bg-background ${defaultTheme} font-sans antialiased`,
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}